services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "5000:5000"
      - "5050:5050"
  catalog.database:
    image: postgres:16.6
volumes:
  postgres_data:   
      


  