services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  catalog.database:
    image: postgres:16.6

  basket.database:
    image: postgres:16.6

volumes:
  postgres_data:
  postgres_basket:
