services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "5000:5000"
      - "5050:5050"

  catalog.database:
    image: postgres:16.6
    container_name: catalog.database
    environment:
      - POSTGRES_DB=catalogDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
   postgres_data:   
      